package mediaktor.koin

import mediaktor.core.exceptions.DIException
import org.koin.core.module.Module

/**
 * This function is a stub for generated function `mediaktor.koin.provideMediator`. The name should resolve to function
 * generated by [preprocessing.processors.HandlerProcessor] as dictated by
 * [Kotlin specification](https://kotlinlang.org/spec/overload-resolution.html) section `11.4.2`.
 *
 * @see DIException
 */
fun Module.provideMediator(arg: Unit = Unit): Nothing = throw DIException("Unable to overload mediaktor.koin.provideMediator() function" +
        "for Koin. This is a bug. Report it at https://github.com/Hashibane/MediaKtor")
