package mediaktorKoin

import exceptions.DIException
import org.koin.core.module.Module
/*
* This function is never supposed to be called as it should resolve to the function generated by the preprocessor.
* The generated mediaktorKoin.provideMediator function has signature Module.() -> Unit and so will have overloading priority during
* compile time (and after the preprocessing).
* https://kotlinlang.org/spec/overload-resolution.html - 11.4.2
 */

fun Module.provideMediator(arg: Unit = Unit): Nothing = throw DIException("Unable to overload mediaktorKoin.provideMediator() function" +
        "for Koin. This is a bug. Report it at https://github.com/Hashibane/MediaKtor")
